### ISSUE TITLE
House Rules

### ISSUE THREAD

**Issue by AwesomeShare** [OldManAlpha/Monopoly-Deal#1]
In the readme, you mention your version uses your house rules.

Can you elaborate on what your house rules are in regards to Monopoly Deal?

**Comment by OldManAlpha** [comment]
I think in order to explain the house rules, I'd have to literally rewrite the rules of Monopoly Deal since they're so ambiguous in a lot of places. I'm mostly saying "house rules" in that you don't often find two groups of Monopoly Deal players who go by exactly the same rules, since there's some blanks people naturally have to fill in along the way. Example being, does a player using a Just Say No! to combat a Just Say No! played against them consume a turn? There's also been a few personal changes that my friend group believes better the game or we misinterpreted when discovering the game. Example being, we draw 5 cards the moment we run out of cards rather than on the next turn(resulting in +2 cards).

I will document the rules at some point, but that might be when I make it so most of the rules are configurable. Not sure when that will happen.

**Comment by OldManAlpha** [comment]
Customizable game rules are being added in the next release using the `/rules` command, so I'm considering this issue to be solved.
